apiVersion: v1
kind: Service
metadata:
  name: youtube-mood-backend
  namespace: youtube-mood
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
spec:
  selector:
    app: youtube-mood-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
