apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-mood-frontend
  namespace: youtube-mood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-mood-frontend
  template:
    metadata:
      labels:
        app: youtube-mood-frontend
    spec:
      containers:
        - name: frontend
          image: youtube-mood-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
