apiVersion: v1
kind: ConfigMap
metadata:
  name: youtube-mood-config
  namespace: youtube-mood
data:
  AWS_REGION: "ap-northeast-2"
  COGNITO_REGION: "ap-northeast-2"
  COGNITO_USER_POOL_ID: ""
  COGNITO_APP_CLIENT_ID: ""
  OPENSEARCH_ENDPOINT: "https://vpc-youtube-mood-nza2no2fobrplq2gbfvxe27xmy.ap-northeast-2.es.amazonaws.com"
  OPENSEARCH_INDEX: "youtube-mood-search-records"
  OPENSEARCH_REGION: "ap-northeast-2"
  OPENSEARCH_SERVICE: "es"
  BEDROCK_ENABLED: "false"
  BEDROCK_MODEL_ID: "anthropic.claude-opus-4-7"
